- name: "main | install awx versionized| setup awx services"
  command: "pip install ."
  args:
    chdir: "/opt/awx/current"
  become: True
  become_user: "{{ awx_user }}"
  when: awx_image_version is defined

  
