#- name: "prepare-server | Enable EPEL Repository on CentOS 8"
#  environment: 
#    ARCH: "{{ ansible_architecture }}"
#  command: "subscription-manager repos --enable 'codeready-builder-for-rhel-8-${ARCH}-rpms'"
#  become: True
#  when: ansible_facts['os_family'] == 'RedHat'
- name: "prepare-server | Ensure dependencies are installed."
  dnf:
    pkg: [
                'jq',
                'redis',
                'nginx',
                'git',
                'gcc-c++',
                'npm',
                'device-mapper-persistent-data',
                'lvm2',
                'bzip2',
                'python3-pip',
                'gcc',
                'openldap-devel',
                'xmlsec1-openssl',
                '@Development Tools',
                'python3.9',
                'postgresql-server'
        ]
  become: true
  when: ansible_facts['os_family'] == 'RedHat'

- name: "prepare-server | Install packages from powertools"
  yum:
    name:
      - xmlsec1-devel
      - libtool-ltdl-devel
      - mlocate
      - libpq-devel
    state: latest
    enablerepo: "powertools"
  become: True
  when: ansible_facts['os_family'] == 'RedHat'

- name: "prepare-server | Add the group {{ awx_user }} with a specific gid"
  ansible.builtin.group:
    name: "{{ awx_user }}"
    state: present
    gid: 1666
  become: True

- name: "prepare-server | Add the user {{ awx_user }} with a specific uid and a primary group of {{ awx_user }}"
  ansible.builtin.user:
    name: "{{ awx_user }}" 
    comment: awx service accout
    uid: 1666
    group: "{{ awx_user }}"
  become: true 

- name: "prepare-server | Create log dir"
  file:
    path: /var/log/tower
    owner: "{{ awx_user }}"
    group: "{{ awx_user }}"
    state: directory
    mode: "u=rwx,g=rwx,o=r"
  become: true

- name: "prepare-server | Create  /var/lib/awx/rsyslog"
  file:
    path: /var/lib/awx/rsyslog
    owner: "{{ awx_user }}"
    group: "{{ awx_user }}"
    state: directory
    mode: "u=rwx,g=rwx,o=r"
  become: true

- name: "prepare-server | Create awx home"
  file:
    path: /var/lib/awx
    owner: "{{ awx_user }}"
    group: "{{ awx_user }}"
    state: directory
    mode: "u=rwx,g=rwx,o=r"
  become: true

- name: "prepare-server | create temporary directory"
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: git_dir

- name: "debug | show tempdir"
  debug:
    var: git_dir.path

- name: "prepate-server | ensure dir exists"
  ansible.builtin.file:
    path: /opt/awx/git
    state: directory
    owner: "{{ awx_user }}"
    group: "{{ awx_user }}"
    mode: "u=rwx,g=rwx,o=r"
  become: True


- name: "prepare-server | check if directory /opt/awx/git/awx-{{ awx_image_version }} exists"
  ansible.builtin.stat:
    path: /opt/awx/git/awx-{{ awx_image_version }}
  register: git_dir

- name: "prepare-server | if not exists clone dir"
  ansible.builtin.git:
    repo: 'https://github.com/ansible/awx.git'
    dest: "/opt/awx/git/awx-{{ awx_image_version }}"
    version: "{{ awx_image_version }}"
    force: True
  become: True
  when: git_dir.stat.exists == False


- name: "prepare-server | Copy awx to /opt/awx-{{ awx_image_version }}"
  ansible.builtin.copy:
    src: "/opt/awx/git/awx-{{ awx_image_version }}"
    dest: "/opt/awx"
    owner: "{{ awx_user }}"
    group: "{{ awx_user }}"
    remote_src: True
  become: True

- name: "prepate-server | delete temporary dir"
  ansible.builtin.file:
    path: /var/tmp/awx-{{ awx_image_version }}"
    state: absent
  become: True

- name: "prepare-server | Recursively change ownership of the directory /etc/tower/conf.d"
  ansible.builtin.file:
    path: /etc/tower/conf.d
    state: directory
    recurse: yes
    owner: "{{ awx_user }}"
    group: "{{ awx_user }}"
  become: True


- name: "prepare-server | set owener /run/tower"
  ansible.builtin.file:
    path: /run/tower
    state: directory
    owner: "{{ awx_user }}"
    group: nginx
  become: True

- name: "prepare-server | Recursirely change ownership of the directory /tmp/awx"
  ansible.builtin.file:
    path: "{{ virtualenvroot }}"
    state: directory
    recurse: yes
    owner: "{{ awx_user }}"
    group: "{{ awx_user }}"
  become: True

- name: "prepare-server | Recursirely change ownership of the directory /tmp/awx"
  ansible.builtin.file:
    path: "/opt/awx-{{ awx_image_version }}"
    state: directory
    recurse: yes
    owner: "{{ awx_user }}"
    group: "{{ awx_user }}"
  become: True


- name: "prepare-server | adding nginx to group {{ awx_user }}"
  user:
    name: nginx
    groups: "{{ awx_user }}"
    append: yes
  become: True
